spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:


server:
  port: 8090

mybatis:
  type-aliases-package: com.example.prac4_db_application.domain
  configuration:
    map-underscore-to-camel-case: true

logging.level.org.hibernate :
  SQL : DEBUG

